### ISSUE TITLE
[Feature] Aumentar número de cajas

### ISSUE THREAD

**Issue by LavenderG** [Raguzero/Midele-Emerald#10]
Aumentar número de cajas de 14 a 18 o 19.

Ver [aquí](https://www.pokecommunity.com/showthread.php?p=10128692#post10128692) y [aquí](https://github.com/cfmnephrite/pokeemerald/commit/443e97361b0c156dde2d6d65bcce5452b979aa5d).

**Comment by Raguzero** [comment]
Idea descartada. No merece la pena aumentar el número de cajas para el embrollo que hay que hacer, que además aun haciendolo para tener 15 o 17 cajas, surgen bugs aleatorios Así que cierro. :lock:
