### ISSUE TITLE
[Feature] Mejorar IA de entrenadores

### ISSUE THREAD

**Issue by LavenderG** [Raguzero/Midele-Emerald#12]
*Marcar cuando se solucione*
- [x] 1-Sharpedo me tiró Taunt dos veces seguidas (estaba yo Taunt ya), posiblemente porque se cambió la forma en que funciona Taunt, ya que se modificó para que dure el efecto 3 turnos en vez de 1.
- [x] 2-Hacer que no sea tonta al usar Endeavor+QuickAttack de los FEAR.
- [x] 3-Debería saber que si tiene la Hab CORROSION puede usar Toxic, Poisonpowder o Poison Gas para envenenar a Pokémon del tipo Poison o Steel.
- [x] 4-Abusa demasiado de usar Protect/Endure/Detect seguidas
- [x] 5-No usar 3 Sleep Talk si usa Rest(son 2 turnos de sueño, no 3)
- [x] 6-No sabe usar Weather Ball al cambiarse su tipo por el clima (Rain = Water, Sun = Fire, Hail = Ice, Sandstorm = Rock)
- [x] 7-Tira Stun Spore, Memento y otras cosas de estado a un Substitute, como si en estos casos no supiese que su enemigo tiene puesto un Substitute. 
- [x] 8-Usa Heal Bell o Aromatherapia cuando no debería (nadie tiene estado alterado en su equipo), ¿o la IA tiene un bug que hace que lo use si tengo pokes con estados alterados en mi equipo?
- [x] 9-Debería cambiar de Pokémon si ese Pokemon tiene la hab Truant ya que se vuelve inútil por su habilidad ante un rival que tenga los ataques Protect, Detect o Substitute.
- [x] 10-La IA no debe usar Taunt contra un Pokémon con la hab OBLIVIOUS (Debido a que Oblivious se actualizó para obtener tambien inmunidad a Taunt).
- [x] 11-¿La IA cambia de pokemon si lo necesita cuando usa un Pokémon Fantasma  (Se actualizó midele para que un Fantasma pueda huir de una habilidad trampa, es decir Shadow Tag, y Arena Trap)
- [x] 12-¿La IA  cambia de pokemon si lo necesita cuando usa un Pokémon con hab Shadow Tag frente a otro Pokémon con hab Shadow Tag? (Se actualizó midele para que un shadow tag pueda huir de otro shadow tag)
- [x] 14-Evitar que la IA cambie todo el rato de Pokémon si sus pokemon son de niveles muy bajos por hacer poco daño (esto sobre todo pasa con los Choice). También pasa en casos como este:  Koomo Specs sale a batalla y cambia todo el rato y parece ser que porque Vaporeon es Max HP y SDef, por lo que recibe poco daño.
- [x] 15-Se sospecha que si le bajas -2 Atk a la IA, y esta tiene Hidden Power / Weather Ball, mira el tipo fisico Normal en vez del resultante, y por tanto cambia de poke. Y que, simétricamente, si lo que le bajas es el Ataque Especial no cambia de poke.
- [x] 17-¿La IA deberia trollear mas con subs, protect, etc. si el rival tiene Truant?
- [x] 18-La IA no sabe usar bien Low Kick(hab Light Metal tambien supongo), Return, Frustration, Eruption, Water Spout, Seismic Toss, Night Sahde por ser daño variable.
- [x] 19-¿La IA sabe usar bien Pain Split? (Parece que por ejemplo Misdreavus con Shadow Ball, thunderwave, confuse ray, pain split VS pokemon tipo Normal spamea Pain Split aunque pierda vida)
Supongo que bastará con bajarle muchos puntos a Pain Split si el rival tiene poca vida y no se puede curar, o si atacará antes que el rival y tiene más vida que el rival. Así puede que cambie
- [x] 20-La IA no sabe usar bien Focus Punch (por ejemplo, deberia usarlo protegido de Substitute, no spamearlo sin ello solo porque su rival es debil a Lucha)
- [x] 21-Parece que la IA prefiere suicidarse con Double Edge mate o no al rival. ¿Deberia tener en cuenta Rock Head a la hora de atacar?
- [ ] 22-La IA con Gliscor Toxic + Protect + EQ + Subs hace el tonto vs Skarmory, además no cambia ni aunque Gliscor quede envenenado.
- [x] 23-Yanmega con Protect, Solar Beam, Thief y Psychic prefiere spamear todo el rato Protect incluso con arena activada haciendole daño, ante Honckrow o Mega Mawile.
- [x] 24-La IA con efecto Encore no cambia ni aunque quede encerrada con un ataque inutil vs el rival (ejemplo lanzallamas vs un absorb fuego). Debería cambiar en los casos que sea inutil quedarse.
- [ ] 25-¿Como reacciona la IA ante torment y attract? (con torment y attract deberia cambiar en algun momento ya que el efecto nunca acaba)
- [x] 26-Si el rival tiene un mov tipo Recover o Rest y ataca antes que la IA, no debe elegir por igual entre todos los movs que llegan al KO. Como mucho, puede elegir entre los que lleguen al KO incluso tras Recover o Rest, si los hay
- [ ] 27-Estaria bien que en dobles, la IA sepa que su aliado va a usar Protect, para asi usar ataques multicampo (surf, eq, boomburst) sin peligro.
- [x] 28-Otro problema que veo es, y tambien lo he visto en el nuzlocke de eeveeto, y es que si llevas un pokemon bruto que hara KO si o si, la IA se boostee con Swords dance en vez de atacar
Esta arreglado solo si la IA ya conoce los ataques.
- [ ] 29-Hm, en el bonus a los ataques que son suficientes para el KO, cuando el poke actual es el último de la IA pero el rival tiene más pokes, tal vez convendría que el juego pensase un poco mejor el ataque a elegir, porque seguramente sea el último que pueda elegir en todo el combate. Por ejemplo, aunque Quick Attack pueda ser KO, ahora mismo recibe más puntos que el resto de movs que lleguen al KO (incluso si el rival ya es más lento y no tiene prioridad), lo que puede hacer que la IA lo tire siempre que pueda, pero si al siguiente poke no le hace KO se puede quedar vendido. O puede que, teniendo un mov que hace OHKO a todo lo que le queda al rival, tire otro que también le hace OHKO al poke que tiene enfrente pero no al resto. Lo dejo anotao pa mañana, te uso de libreta
- [x] 30-Sobre Technician: Afecta a Pursuit aunque tenga el doble de potencia. Se ve que el juego duplica el daño o el Ataque, en lugar de la potencia.
Lo mismo con Struggle (en 4ª no lo hace pero en 7ª sí) y que potencia confusión
- [x] 31-No usar Heal Bell si tienes estado alterado y estas apunto de morir (tal vez si usarlo si el equipo tiene estados)
- [ ] 32-Estaria bien que un usuario de Wish cambiase de poke para curar a otro pokemon y que dicho pokemon sea capaz de entrar a recibir bien el golpe
- [x] 33-Los pokemon rapidos no se curan con Recover/etc.
- [x] 34-la IA que reciba mud slap o sand attack hasta el punto de quedarse ciego perdido e inutil, termina cambiando?
- [x] 35-Si el rival tiene roar o whirlwind y lo ha usado ya para sacar pokes del campo, la AI no debe ponerse usar substitute o ponerse a boostearse con comic power y cosas defensivas (o tal vez no boostearse con nada) justo delante de él
- [x] 36-Solar Beam no funciona bien, no deberia usarlo si tienes otro ataques que van a hacer KO.
- [x] 37-SUBS IA --> -Feraligatr  {MOVE_WILL_O_WISP, MOVE_SURF, MOVE_LOCK_ON, MOVE_HYDRO_BEAM}   Prefiere tirar Hyper Beam(101) antes que Surf(100) si Espeon tiene 142/334 y tiene Substitute (rompe el Subs con Hyper Beam, pero no con Surf)
- [x] 38-La IA no sabe que vas a tirar Subs de nuevo siendo mas rápido, perdiendo turno por tirar algo que no afecte a subs siendo mas lento

**Comment by Raguzero** [comment]
El resto de IAs no se hará. Cierro esto.
