### ISSUE TITLE
[Bug] Error gráfico en ciertas rutas de agua

### ISSUE THREAD

**Issue by LavenderG** [Raguzero/Midele-Emerald#2]
**Describe the bug**
Error gráfico en las rutas de agua que han sido modificadas que provoca que en ocasiones, al usar Surf o Vuelo el sprite del Pokémon aparezca con una paleta distinta.

**To Reproduce**
1. Ve a Ciudad Algaria.
2. Usa Surf desde la izquierda y llega a tierra sin tener ningún combate.
3. Sitúate sobre la hierba que está sobre la arena.
4. Usa Vuelo a Ciudad Algaria.

**Expected behavior**
El sprite se debería mostrar correctamente.

**Screenshots**
![Pantalla con el bug presente](https://i.imgur.com/bgnef7u.png)
Pantalla con el bug presente.

**Additional context**
Relacionado con commits bb9115f066888f8cb7cc6e9574c6c513026e4936 y d0f47e0313398fe85f79149cb59ee7dd463028f3.

**Comment by Manectric-Rang** [comment]
He afinado la situación en la que sucede este bug y he averiguado cuál es la causa: falta espacio en el buffer de paletas de sprites.

Hasta donde he podido ver, el bug se produce en estas rutas acuáticas exactamente cuando el jugador se encuentra en un cuadro con hierba y el jugador está a tres o menos pasos de que un NPC aparezca en el campo de visión. A continuación explico el probable mecanismo por el que esto sucede.

En primer lugar, la paleta de sprites almacena los colorines de los sprites que hay o puede haber en pantalla. Está formada por 16 filas con 16 colores cada una. A la hora de volar, la paleta del pokémon se almacena y se lee en la última fila.

Cuando el jugador se encuentra sobre hierba, el juego no dibuja la hierba que es pisada por el jugador como background, como hace habitualmente, sino como sprite, con el objetivo de mostrar la animación. Por tanto, al pisar la hierba se asigna una fila en la paleta de sprites para los colores de la hierba, que en las rutas marítimas parece situarse siempre en la penúltima fila. Cuando el jugador no pisa esta hierba, no es necesario que se mantengan en la paleta los colores de la hierba.

En estas rutas marítimas, los colores de los NPC parecen almacenarse siempre en la fila siguiente a la de la hierba, o en la penúltima si el jugador no está sobre la hierba.

Esto último provoca que, si el jugador está sobre la hierba, la paleta de los NPC se almacene en la última fila, dado que mantiene los colores de la hierba y de los NPC. Esto le quita el sitio a la paleta del poke (probablemente se escribe pero es sobreescrita inmediatamente por la de los NPC) y genera el bug.

Posibles soluciones:
 - Hacer sitio en otro lugar en la paleta de sprites, de forma que la paleta de los NPC se pueda situar antes. Esto seguramente es lo que sucede en las otras rutas, por lo que es probablemente la solución más limpia, pero no está claro si es viable hacer esto; requeriría entender por qué hay tantas filas usadas en la paleta de sprites (los árboles, el agua, el agua profunda, el agua poco profunda, las rocas, las rocas azules y demás no ocupan espacio en esta paleta, son background todo).
 - A la hora de volar, no es necesario que se tenga el sprite de la hierba donde pisa el jugador, dado que no se va a mostrar ninguna animación ahí. Por tanto, se podría solucionar eliminando el sprite de hierba donde se encuentra el jugador cuando va a volar. Esto puede no ser fácil de hacer, y podría no servir o dar problemas para otros _field effects_ que sí puedan provocar animación del cuadro de hierba (¿los hay?) o que no hagan que el jugador abandone inmediatamente la ruta (¿los hay? Corte no cuenta, porque igualmente va a eliminar el sprite. Surf puede contar pero es fácil hacer que los mapas no tengan hierba junto a las orillas).
 - Modificar las rutas de agua para que los NPCs siempre estén bien lejos de la hierba. Es mucho espacio el que hay que dejar a los NPCs, parece inviable aunque definitivamente se puede hacer.

Puede haber más soluciones, pero no se me ocurren en este momento.

**Comment by Raguzero** [comment]
Bug gráfico en la Ruta 104 y 128 cuando usas el Dexnav para buscar Pokemon en la hierba (y probablemente en zonas donde haya hierbas y mar al mismo tiempo)
imagen

**Comment by Raguzero** [comment]
Corregido el bug:
https://github.com/Raguzero/Midele-Emerald/commit/537c1ba0e0fc1a6fddc711e3820b76152c5ef734

Cierro esto.

**Comment by Manectric-Rang** [comment]
Al final lo que se ha hecho es almacenar en otro sitio la paleta del bicho de turno.
 - Para el problema del mensaje inicial, la paleta se almacena, si no hay sitio en los espacios donde se pone de serie, en el espacio reservado para la paleta de la tormenta de arena de la ruta 111 y de las nubes de la ruta 120 (que se ven en los charcos y charcas), aprovechando que el problema no se da en ninguna de esas dos rutas.
 - Para el problema del dexnav, se lía un importante pifostio, pero se hace algo con la misma idea:
    - Fuera de las rutas 111 y 120, se almacena en el espacio reservado para la paleta de la tormenta de arena y las nubes, dado que no hay ninguna de esas cosas.
    - En la ruta 111, si buscas en tierra (y por tanto en arena, no hay más tierra) se almacena donde lo hace de serie, dado que ahí no se buguea; si buscas en el agua se maneja como el anterior.
    - En la ruta 120, si todavía no se tiene el Devon Scope, se almacena en el espacio de la tormenta y las nubes, dado que no es posible estar donde las nubes todavía, mientras que si ya se tiene el Devon Scope se almacena en el espacio 11, que en esa ruta solo se almacena para la sombra de un Kecleon que desaparece en cuanto se adquiere el Devon Scope.
