### ISSUE TITLE
[¿Bug?] Habilidad TRACE no activa INTIMIDATE

### ISSUE THREAD

**Issue by Raguzero** [Raguzero/Midele-Emerald#23]
TRACE al copiar INTIMIDATE nunca activa dicha habilidad y por tanto no reduce el ATAQUE del enemigo.  Es posible que ocurra con otras habilidades con efecto parecida, y que esto se deba a como funcionan los juegos de la 3ª generación. (tal vez no se deba considerar un bug, y pasa en el juego original también)

**Comment by LavenderG** [comment]
Acabo de comprobarlo y también ocurre en el juego original.

**Comment by Raguzero** [comment]
No merece la pena arreglarlo (solo la familia Porygon y Ralts lo tienen), cierro.
