### ISSUE TITLE
[Bug] Multihits poderosos contra Sturdy solo hace 1 hit

### ISSUE THREAD

**Issue by Raguzero** [Raguzero/Midele-Emerald#33]
Cuando usas un ataque poderoso Multihit (ejemplo Bullet Seed) capaz de debilitar de un golpe
contra un Pokémon con Sturdy que tiene el máximo de HP (que es lo que hace que active Sturdy) solo hace 1 hit y no debilita al Pokémon ya que no realiza mas hits.

Esto no ocurre si el primer hit del ataque multihit no debilita de un golpe (debido a que Sturdy no se activa, como debe ser).

**Comment by LavenderG** [comment]
Arreglado en https://github.com/Raguzero/Midele-Emerald/commit/dbfad134ddac273214c6d4b79bb37264f7c74074

Ahora Sturdy solo se activaría en el primer golpe del multihit si se tiene toda la vida.
