### ISSUE TITLE
Mejorar el Level Cap para evitar farmeos extremos 

### ISSUE THREAD

**Issue by Raguzero** [Raguzero/Midele-Emerald#34]
Se debería mejorar el level cap para que siga funcionando después de conseguir las 8 medallas, para todo lo relativo del postgame. 

De esta forma evitaríamos que se pudiese farmear niveles con las 23823892 revanchas que existen, lo que podría hacer el postgame demasiado fácil.

También evitaria que debido a como funciona el DexNav se pueda conseguir un magikarp nv60/70/80/90... a pesar de que se puso que salga solo al nv100 en cierta ruta (al nv100 no podrías tener un potente gyarados al no poder subir nivel para evolcionar en él).

**Comment by LavenderG** [comment]
https://github.com/Raguzero/Midele-Emerald/commit/5f5df0f671d0f190f1384082625fde4dddfb9a04

Falta actualizar los niveles (sCapLevels) y flags (sLevelCapFlags).

**Comment by Raguzero** [comment]
Actualizado, y ya solo falta cambiarlo sobre la marcha los numeros de niveles si no concuerdan con la zona del juego.  Cierro esto. :lock:
