### ISSUE TITLE
[Bug] Cambio de forma en Deoxys, no selecciona cual Deoxys

### ISSUE THREAD

**Issue by Raguzero** [Raguzero/Midele-Emerald#36]
El nuevo evento de Fallarbor Town que permite cambiar de forma a Deoxys necesita tener el script de elegir Pokémon para elegir cual Deoxys quieres cambiar de forma, ya que sino, si tienes mas de 1 Deoxys, cambia de forma el Deoxys mas arriba de la posición del equipo.

**Comment by LavenderG** [comment]
Arreglado en https://github.com/Raguzero/Midele-Emerald/commit/85737e2926cd7c012c25713774b88c21bb7b1467

Ahora puedes elegir el DEOXYS del equipo.
