### ISSUE TITLE
[Bug] Casilla de combate de Gym gooses

### ISSUE THREAD

**Issue by LavenderG** [Raguzero/Midele-Emerald#42]
Después de caer en ella, vencer en combate y tirar el dado, la casilla en la que caes no se activa y te puedes mover a otra casilla de al lado si quieres, lo cual no debería ocurrir. Debería activarse la casilla en la que caes tras tirar el dado.

**Comment by Raguzero** [comment]
Corregido.
https://github.com/Raguzero/Midele-Emerald/commit/a8ee1541f94d967b0a4749c57eb70530674e5148

Cierro.
