### ISSUE TITLE
[Bug] Descripción de objeto incorrecta al cancelar la ordenación de bolsa

### ISSUE THREAD

**Issue by LavenderG** [Raguzero/Midele-Emerald#5]
**Describe the bug**
La descripción del objeto de la bolsa tras cancelar la ordenación de la bolsa es incorrecta. En vez de mostrar la descripción del objeto seleccionado, siempre muestra la descripción del primero objeto de la bolsa.

**To Reproduce**
1. Abre la bolsa.
2. Selecciona un bolsillo en el que se tienen varios objetos.
3. Mueve el cursor a un objeto que no sea el primero.
4. Pulsa **START** (abre el menú de ordenación).
5. Pulsa **B** (cancela la ordenación)
6. Ahora la descripción del objeto seleccionado será la del primer objeto.

**Expected behavior**
Al cancelar el menú de ordenación se debería mostrar la descripción del objeto seleccionado, o colocar el cursor en el primer objeto para cuadrar con la descripción mostrada.

**Screenshots**
![Objeto G PROTEIN mostrando la descripción de PP MAX.](https://user-images.githubusercontent.com/42317903/106943922-e8a87a00-671d-11eb-9727-14e729a34bb9.png)
Objeto G PROTEIN mostrando la descripción de PP MAX.

**Additional context**
Relacionado con los commits 743d34280b7b70c22d1c240055e5c49d41e1586a y bf0ca715af914346cd099c066ec3ee7f64eade48.

**Comment by Raguzero** [comment]
Corregido.
https://github.com/Raguzero/Midele-Emerald/commit/b16aed9d335fe91f21d7499c409c10948b3057d8
