### ISSUE TITLE
[Bug] Color incorrecto en sprites overworld de nuevos legendarios

### ISSUE THREAD

**Issue by LavenderG** [Raguzero/Midele-Emerald#6]
**Describe the bug**
Los colores de los sprites overworld de los nuevos legendarios (Entei, Suicune, Raikou, Articuno, Zapdos, Moltres, Mewtwo y Celebi) no son mostrados de forma correcta.

**To Reproduce**
1. Coloca un sprite de los mencionados anteriormente o ve donde ya hay uno posicionado (ejemplo: Raikou en Ruta 114).
2. El sprite overworld no muestra el color que debería.

**Expected behavior**
Los sprites deberían mostrar la paleta de colores correcta.

**Screenshots**
![Sprite overworld de Raikou](https://user-images.githubusercontent.com/42317903/106945463-ba2b9e80-671f-11eb-9979-680c7854dfa3.png)
Sprite overworld de Raikou.

**Comment by Raguzero** [comment]
Corregido:
https://github.com/Raguzero/Midele-Emerald/commit/9df9c03c89abab8dda8c297fe3b6406e9bef8f0c
