### ISSUE TITLE
[Bug] Error de color en la nueva transición

### ISSUE THREAD

**Issue by LavenderG** [Raguzero/Midele-Emerald#7]
**Describe the bug**
La transición B_TRANSITION_MONITO muestra unos colores incorrectos.

**To Reproduce**
1. Añadir la transición B_TRANSITION_MONITO a un tipo de combate.
2. Iniciar un combate de ese tipo.
3. La transición es mostrada con un color incorrecto.

**Expected behavior**
La transición debería mostrarse con un color correcto.

**Screenshots**
![Pantalla de transición con color incorrecto](https://user-images.githubusercontent.com/42317903/106946440-00353200-6721-11eb-9995-9e9110014f92.png)
Pantalla de transición con color incorrecto.

**Additional context**
Relacionado con commits dbc45153e84a322cdc340e72271bf00971944991 y 9baa15a55ebfbccbdf09775e02280455abd2973c.

**Comment by Raguzero** [comment]
Corregido.
https://github.com/Raguzero/Midele-Emerald/commit/ccb047b78125e504eeaedd60abd78a1692b7cb89
